package models

import (
	"hilive/modules/db"
	"hilive/modules/db/command"
	"hilive/modules/utils"
	"log"
	"testing"
)

// 從mysql查詢所有遊戲資料，寫入mongo中
func Test_Game_Mongo(t *testing.T) {
	var (
		data = make([]interface{}, 0)

		allFields = []string{
			"user_id",
			"activity_game.activity_id",
			"activity_game.game_id",
		}

		// 扭蛋機-----start
		gachaMachinefields = []string{
			"user_id",
			"activity_id",
			"game_id",
			"game",
			"topic",
			"skin",
			"music",
			"game_status",
			"game_order",
			"title",
			"allow",
			"max_times",
			"percent",
			"reflective_switch",
			"gacha_machine_reflection",
			"game_round",
			"game_second",
			"game_attend",
			"edit_times",
			// "created_at",
			// "updated_at",

			// 扭蛋遊戲自定義
			"3d_gacha_machine_classic_h_pic_02",
			"3d_gacha_machine_classic_h_pic_03",
			"3d_gacha_machine_classic_h_pic_04",
			"3d_gacha_machine_classic_h_pic_05",
			"3d_gacha_machine_classic_g_pic_01",
			"3d_gacha_machine_classic_g_pic_02",
			"3d_gacha_machine_classic_g_pic_03",
			"3d_gacha_machine_classic_g_pic_04",
			"3d_gacha_machine_classic_g_pic_05",
			"3d_gacha_machine_classic_c_pic_01",

			// 音樂
			"3d_gacha_machine_bgm_gaming", // 遊戲進行中
		}

		// 扭蛋機-----end

		// 賓果-----start
		bingofields = []string{
			"user_id",
			"activity_id",
			"game_id",
			"game",
			"topic",
			"skin",
			"music",
			"game_status",
			"game_order",
			"title",
			"max_people",
			"people",
			"allow",
			"max_number",
			"bingo_line",
			"round_prize",
			"game_round",
			"game_second",
			"game_attend",
			// "bingo_round",
			"edit_times",

			// 賓果遊戲自定義
			// 音樂
			"bingo_bgm_start",  // 遊戲開始
			"bingo_bgm_gaming", // 遊戲進行中
			"bingo_bgm_end",    // 遊戲結束

			"bingo_classic_h_pic_01",
			"bingo_classic_h_pic_02",
			"bingo_classic_h_pic_03",
			"bingo_classic_h_pic_04",
			"bingo_classic_h_pic_05",
			"bingo_classic_h_pic_06",
			"bingo_classic_h_pic_07",
			"bingo_classic_h_pic_08",
			"bingo_classic_h_pic_09",
			"bingo_classic_h_pic_10",
			"bingo_classic_h_pic_11",
			"bingo_classic_h_pic_12",
			"bingo_classic_h_pic_13",
			"bingo_classic_h_pic_14",
			"bingo_classic_h_pic_15",
			"bingo_classic_h_pic_16",
			"bingo_classic_g_pic_01",
			"bingo_classic_g_pic_02",
			"bingo_classic_g_pic_03",
			"bingo_classic_g_pic_04",
			"bingo_classic_g_pic_05",
			"bingo_classic_g_pic_06",
			"bingo_classic_g_pic_07",
			"bingo_classic_g_pic_08",
			"bingo_classic_c_pic_01",
			"bingo_classic_c_pic_02",
			"bingo_classic_c_pic_03",
			"bingo_classic_c_pic_04",
			"bingo_classic_h_ani_01",
			"bingo_classic_g_ani_01",
			"bingo_classic_c_ani_01",
			"bingo_classic_c_ani_02",

			"bingo_newyear_dragon_h_pic_01",
			"bingo_newyear_dragon_h_pic_02",
			"bingo_newyear_dragon_h_pic_03",
			"bingo_newyear_dragon_h_pic_04",
			"bingo_newyear_dragon_h_pic_05",
			"bingo_newyear_dragon_h_pic_06",
			"bingo_newyear_dragon_h_pic_07",
			"bingo_newyear_dragon_h_pic_08",
			"bingo_newyear_dragon_h_pic_09",
			"bingo_newyear_dragon_h_pic_10",
			"bingo_newyear_dragon_h_pic_11",
			"bingo_newyear_dragon_h_pic_12",
			"bingo_newyear_dragon_h_pic_13",
			"bingo_newyear_dragon_h_pic_14",
			"bingo_newyear_dragon_h_pic_16",
			"bingo_newyear_dragon_h_pic_17",
			"bingo_newyear_dragon_h_pic_18",
			"bingo_newyear_dragon_h_pic_19",
			"bingo_newyear_dragon_h_pic_20",
			"bingo_newyear_dragon_h_pic_21",
			"bingo_newyear_dragon_h_pic_22",
			"bingo_newyear_dragon_g_pic_01",
			"bingo_newyear_dragon_g_pic_02",
			"bingo_newyear_dragon_g_pic_03",
			"bingo_newyear_dragon_g_pic_04",
			"bingo_newyear_dragon_g_pic_05",
			"bingo_newyear_dragon_g_pic_06",
			"bingo_newyear_dragon_g_pic_07",
			"bingo_newyear_dragon_g_pic_08",
			"bingo_newyear_dragon_c_pic_01",
			"bingo_newyear_dragon_c_pic_02",
			"bingo_newyear_dragon_c_pic_03",
			"bingo_newyear_dragon_h_ani_01",
			"bingo_newyear_dragon_g_ani_01",
			"bingo_newyear_dragon_c_ani_01",
			"bingo_newyear_dragon_c_ani_02",
			"bingo_newyear_dragon_c_ani_03",

			"bingo_cherry_h_pic_01",
			"bingo_cherry_h_pic_02",
			"bingo_cherry_h_pic_03",
			"bingo_cherry_h_pic_04",
			"bingo_cherry_h_pic_05",
			"bingo_cherry_h_pic_06",
			"bingo_cherry_h_pic_07",
			"bingo_cherry_h_pic_08",
			"bingo_cherry_h_pic_09",
			"bingo_cherry_h_pic_10",
			"bingo_cherry_h_pic_11",
			"bingo_cherry_h_pic_12",
			"bingo_cherry_h_pic_14",
			"bingo_cherry_h_pic_15",
			"bingo_cherry_h_pic_17",
			"bingo_cherry_h_pic_18",
			"bingo_cherry_h_pic_19",
			"bingo_cherry_g_pic_01",
			"bingo_cherry_g_pic_02",
			"bingo_cherry_g_pic_03",
			"bingo_cherry_g_pic_04",
			"bingo_cherry_g_pic_05",
			"bingo_cherry_g_pic_06",
			"bingo_cherry_c_pic_01",
			"bingo_cherry_c_pic_02",
			"bingo_cherry_c_pic_03",
			"bingo_cherry_c_pic_04",
			"bingo_cherry_h_ani_02",
			"bingo_cherry_h_ani_03",
			"bingo_cherry_g_ani_01",
			"bingo_cherry_g_ani_02",
			"bingo_cherry_c_ani_01",
			"bingo_cherry_c_ani_02",
		}
		// 賓果-----end

		// 搖號抽獎-----start
		drawNumbersfields = []string{
			"user_id",
			"activity_id",
			"game_id",
			"game",
			"topic",
			"skin",
			"music",
			"game_status",
			"game_order",
			"title",
			"limit_time",
			"second",
			"allow",
			"display_name",
			"game_round",
			"game_second",
			"game_attend",
			"edit_times",

			// 搖號抽獎自定義
			// 音樂
			"draw_numbers_bgm_gaming",

			"draw_numbers_classic_h_pic_01",
			"draw_numbers_classic_h_pic_02",
			"draw_numbers_classic_h_pic_03",
			"draw_numbers_classic_h_pic_04",
			"draw_numbers_classic_h_pic_05",
			"draw_numbers_classic_h_pic_06",
			"draw_numbers_classic_h_pic_07",
			"draw_numbers_classic_h_pic_08",
			"draw_numbers_classic_h_pic_09",
			"draw_numbers_classic_h_pic_10",
			"draw_numbers_classic_h_pic_11",
			"draw_numbers_classic_h_pic_12",
			"draw_numbers_classic_h_pic_13",
			"draw_numbers_classic_h_pic_14",
			"draw_numbers_classic_h_pic_15",
			"draw_numbers_classic_h_pic_16",
			"draw_numbers_classic_h_ani_01",

			"draw_numbers_gold_h_pic_01",
			"draw_numbers_gold_h_pic_02",
			"draw_numbers_gold_h_pic_03",
			"draw_numbers_gold_h_pic_04",
			"draw_numbers_gold_h_pic_05",
			"draw_numbers_gold_h_pic_06",
			"draw_numbers_gold_h_pic_07",
			"draw_numbers_gold_h_pic_08",
			"draw_numbers_gold_h_pic_09",
			"draw_numbers_gold_h_pic_10",
			"draw_numbers_gold_h_pic_11",
			"draw_numbers_gold_h_pic_12",
			"draw_numbers_gold_h_pic_13",
			"draw_numbers_gold_h_pic_14",
			"draw_numbers_gold_h_ani_01",
			"draw_numbers_gold_h_ani_02",
			"draw_numbers_gold_h_ani_03",

			"draw_numbers_newyear_dragon_h_pic_01",
			"draw_numbers_newyear_dragon_h_pic_02",
			"draw_numbers_newyear_dragon_h_pic_03",
			"draw_numbers_newyear_dragon_h_pic_04",
			"draw_numbers_newyear_dragon_h_pic_05",
			"draw_numbers_newyear_dragon_h_pic_06",
			"draw_numbers_newyear_dragon_h_pic_07",
			"draw_numbers_newyear_dragon_h_pic_08",
			"draw_numbers_newyear_dragon_h_pic_09",
			"draw_numbers_newyear_dragon_h_pic_10",
			"draw_numbers_newyear_dragon_h_pic_11",
			"draw_numbers_newyear_dragon_h_pic_12",
			"draw_numbers_newyear_dragon_h_pic_13",
			"draw_numbers_newyear_dragon_h_pic_14",
			"draw_numbers_newyear_dragon_h_pic_15",
			"draw_numbers_newyear_dragon_h_pic_16",
			"draw_numbers_newyear_dragon_h_pic_17",
			"draw_numbers_newyear_dragon_h_pic_18",
			"draw_numbers_newyear_dragon_h_pic_19",
			"draw_numbers_newyear_dragon_h_pic_20",
			"draw_numbers_newyear_dragon_h_ani_01",
			"draw_numbers_newyear_dragon_h_ani_02",

			"draw_numbers_cherry_h_pic_01",
			"draw_numbers_cherry_h_pic_02",
			"draw_numbers_cherry_h_pic_03",
			"draw_numbers_cherry_h_pic_04",
			"draw_numbers_cherry_h_pic_05",
			"draw_numbers_cherry_h_pic_06",
			"draw_numbers_cherry_h_pic_07",
			"draw_numbers_cherry_h_pic_08",
			"draw_numbers_cherry_h_pic_09",
			"draw_numbers_cherry_h_pic_10",
			"draw_numbers_cherry_h_pic_11",
			"draw_numbers_cherry_h_pic_12",
			"draw_numbers_cherry_h_pic_13",
			"draw_numbers_cherry_h_pic_14",
			"draw_numbers_cherry_h_pic_15",
			"draw_numbers_cherry_h_pic_16",
			"draw_numbers_cherry_h_pic_17",
			"draw_numbers_cherry_h_ani_01",
			"draw_numbers_cherry_h_ani_02",
			"draw_numbers_cherry_h_ani_03",
			"draw_numbers_cherry_h_ani_04",

			"draw_numbers_3D_space_h_pic_01",
			"draw_numbers_3D_space_h_pic_02",
			"draw_numbers_3D_space_h_pic_03",
			"draw_numbers_3D_space_h_pic_04",
			"draw_numbers_3D_space_h_pic_05",
			"draw_numbers_3D_space_h_pic_06",
			"draw_numbers_3D_space_h_pic_07",
			"draw_numbers_3D_space_h_pic_08",
		}

		// 搖號抽獎-----end

		// 遊戲抽獎-----start
		lotteryfields = []string{
			"user_id",
			"activity_id",
			"game_id",
			"game",
			"topic",
			"skin",
			"music",
			"game_status",
			"game_order",
			"title",
			"allow",
			"max_times",
			"game_type",
			"game_round",
			"game_second",
			"game_attend",
			"edit_times",

			"lottery_bgm_gaming",

			"lottery_jiugongge_classic_h_pic_01",
			"lottery_jiugongge_classic_h_pic_02",
			"lottery_jiugongge_classic_h_pic_03",
			"lottery_jiugongge_classic_h_pic_04",
			"lottery_jiugongge_classic_g_pic_01",
			"lottery_jiugongge_classic_g_pic_02",
			"lottery_jiugongge_classic_c_pic_01",
			"lottery_jiugongge_classic_c_pic_02",
			"lottery_jiugongge_classic_c_pic_03",
			"lottery_jiugongge_classic_c_pic_04",
			"lottery_jiugongge_classic_c_ani_01",
			"lottery_jiugongge_classic_c_ani_02",
			"lottery_jiugongge_classic_c_ani_03",

			"lottery_turntable_classic_h_pic_01",
			"lottery_turntable_classic_h_pic_02",
			"lottery_turntable_classic_h_pic_03",
			"lottery_turntable_classic_h_pic_04",
			"lottery_turntable_classic_g_pic_01",
			"lottery_turntable_classic_g_pic_02",
			"lottery_turntable_classic_c_pic_01",
			"lottery_turntable_classic_c_pic_02",
			"lottery_turntable_classic_c_pic_03",
			"lottery_turntable_classic_c_pic_04",
			"lottery_turntable_classic_c_pic_05",
			"lottery_turntable_classic_c_pic_06",
			"lottery_turntable_classic_c_ani_01",
			"lottery_turntable_classic_c_ani_02",
			"lottery_turntable_classic_c_ani_03",

			"lottery_jiugongge_starrysky_h_pic_01",
			"lottery_jiugongge_starrysky_h_pic_02",
			"lottery_jiugongge_starrysky_h_pic_03",
			"lottery_jiugongge_starrysky_h_pic_04",
			"lottery_jiugongge_starrysky_h_pic_05",
			"lottery_jiugongge_starrysky_h_pic_06",
			"lottery_jiugongge_starrysky_h_pic_07",
			"lottery_jiugongge_starrysky_g_pic_01",
			"lottery_jiugongge_starrysky_g_pic_02",
			"lottery_jiugongge_starrysky_g_pic_03",
			"lottery_jiugongge_starrysky_g_pic_04",
			"lottery_jiugongge_starrysky_c_pic_01",
			"lottery_jiugongge_starrysky_c_pic_02",
			"lottery_jiugongge_starrysky_c_pic_03",
			"lottery_jiugongge_starrysky_c_pic_04",
			"lottery_jiugongge_starrysky_c_ani_01",
			"lottery_jiugongge_starrysky_c_ani_02",
			"lottery_jiugongge_starrysky_c_ani_03",
			"lottery_jiugongge_starrysky_c_ani_04",
			"lottery_jiugongge_starrysky_c_ani_05",
			"lottery_jiugongge_starrysky_c_ani_06",

			"lottery_turntable_starrysky_h_pic_01",
			"lottery_turntable_starrysky_h_pic_02",
			"lottery_turntable_starrysky_h_pic_03",
			"lottery_turntable_starrysky_h_pic_04",
			"lottery_turntable_starrysky_h_pic_05",
			"lottery_turntable_starrysky_h_pic_06",
			"lottery_turntable_starrysky_h_pic_07",
			"lottery_turntable_starrysky_h_pic_08",
			"lottery_turntable_starrysky_g_pic_01",
			"lottery_turntable_starrysky_g_pic_02",
			"lottery_turntable_starrysky_g_pic_03",
			"lottery_turntable_starrysky_g_pic_04",
			"lottery_turntable_starrysky_g_pic_05",
			"lottery_turntable_starrysky_c_pic_01",
			"lottery_turntable_starrysky_c_pic_02",
			"lottery_turntable_starrysky_c_pic_03",
			"lottery_turntable_starrysky_c_pic_04",
			"lottery_turntable_starrysky_c_pic_05",
			"lottery_turntable_starrysky_c_ani_01",
			"lottery_turntable_starrysky_c_ani_02",
			"lottery_turntable_starrysky_c_ani_03",
			"lottery_turntable_starrysky_c_ani_04",
			"lottery_turntable_starrysky_c_ani_05",
			"lottery_turntable_starrysky_c_ani_06",
			"lottery_turntable_starrysky_c_ani_07",
		}

		// 遊戲抽獎-----end

		// 鑑定師-----start
		monopolyfields = []string{
			"user_id",
			"activity_id",
			"game_id",
			"game",
			"topic",
			"skin",
			"music",
			"game_status",
			"game_order",
			"title",
			"people",
			"max_people",
			"allow",
			"limit_time",
			"second",
			"first_prize",
			"second_prize",
			"third_prize",
			"general_prize",
			"game_round",
			"game_second",
			"game_attend",
			"edit_times",

			"monopoly_bgm_start",
			"monopoly_bgm_gaming",
			"monopoly_bgm_end",

			"monopoly_classic_h_pic_01",
			"monopoly_classic_h_pic_02",
			"monopoly_classic_h_pic_03",
			"monopoly_classic_h_pic_04",
			"monopoly_classic_h_pic_05",
			"monopoly_classic_h_pic_06",
			"monopoly_classic_h_pic_07",
			"monopoly_classic_h_pic_08",
			"monopoly_classic_g_pic_01",
			"monopoly_classic_g_pic_02",
			"monopoly_classic_g_pic_03",
			"monopoly_classic_g_pic_04",
			"monopoly_classic_g_pic_05",
			"monopoly_classic_g_pic_06",
			"monopoly_classic_g_pic_07",
			"monopoly_classic_c_pic_01",
			"monopoly_classic_c_pic_02",
			"monopoly_classic_g_ani_01",
			"monopoly_classic_g_ani_02",
			"monopoly_classic_c_ani_01",

			"monopoly_redpack_h_pic_01",
			"monopoly_redpack_h_pic_02",
			"monopoly_redpack_h_pic_03",
			"monopoly_redpack_h_pic_04",
			"monopoly_redpack_h_pic_05",
			"monopoly_redpack_h_pic_06",
			"monopoly_redpack_h_pic_07",
			"monopoly_redpack_h_pic_08",
			"monopoly_redpack_h_pic_09",
			"monopoly_redpack_h_pic_10",
			"monopoly_redpack_h_pic_11",
			"monopoly_redpack_h_pic_12",
			"monopoly_redpack_h_pic_13",
			"monopoly_redpack_h_pic_14",
			"monopoly_redpack_h_pic_15",
			"monopoly_redpack_h_pic_16",
			"monopoly_redpack_g_pic_01",
			"monopoly_redpack_g_pic_02",
			"monopoly_redpack_g_pic_03",
			"monopoly_redpack_g_pic_04",
			"monopoly_redpack_g_pic_05",
			"monopoly_redpack_g_pic_06",
			"monopoly_redpack_g_pic_07",
			"monopoly_redpack_g_pic_08",
			"monopoly_redpack_g_pic_09",
			"monopoly_redpack_g_pic_10",
			"monopoly_redpack_c_pic_01",
			"monopoly_redpack_c_pic_02",
			"monopoly_redpack_c_pic_03",
			"monopoly_redpack_h_ani_01",
			"monopoly_redpack_h_ani_02",
			"monopoly_redpack_h_ani_03",
			"monopoly_redpack_g_ani_01",
			"monopoly_redpack_g_ani_02",
			"monopoly_redpack_c_ani_01",

			"monopoly_newyear_rabbit_h_pic_01",
			"monopoly_newyear_rabbit_h_pic_02",
			"monopoly_newyear_rabbit_h_pic_03",
			"monopoly_newyear_rabbit_h_pic_04",
			"monopoly_newyear_rabbit_h_pic_05",
			"monopoly_newyear_rabbit_h_pic_06",
			"monopoly_newyear_rabbit_h_pic_07",
			"monopoly_newyear_rabbit_h_pic_08",
			"monopoly_newyear_rabbit_h_pic_09",
			"monopoly_newyear_rabbit_h_pic_10",
			"monopoly_newyear_rabbit_h_pic_11",
			"monopoly_newyear_rabbit_h_pic_12",
			"monopoly_newyear_rabbit_g_pic_01",
			"monopoly_newyear_rabbit_g_pic_02",
			"monopoly_newyear_rabbit_g_pic_03",
			"monopoly_newyear_rabbit_g_pic_04",
			"monopoly_newyear_rabbit_g_pic_05",
			"monopoly_newyear_rabbit_g_pic_06",
			"monopoly_newyear_rabbit_g_pic_07",
			"monopoly_newyear_rabbit_c_pic_01",
			"monopoly_newyear_rabbit_c_pic_02",
			"monopoly_newyear_rabbit_c_pic_03",
			"monopoly_newyear_rabbit_h_ani_01",
			"monopoly_newyear_rabbit_h_ani_02",
			"monopoly_newyear_rabbit_g_ani_01",
			"monopoly_newyear_rabbit_g_ani_02",
			"monopoly_newyear_rabbit_c_ani_01",

			"monopoly_sashimi_h_pic_01",
			"monopoly_sashimi_h_pic_02",
			"monopoly_sashimi_h_pic_03",
			"monopoly_sashimi_h_pic_04",
			"monopoly_sashimi_h_pic_05",
			"monopoly_sashimi_g_pic_01",
			"monopoly_sashimi_g_pic_02",
			"monopoly_sashimi_g_pic_03",
			"monopoly_sashimi_g_pic_04",
			"monopoly_sashimi_g_pic_05",
			"monopoly_sashimi_g_pic_06",
			"monopoly_sashimi_c_pic_01",
			"monopoly_sashimi_c_pic_02",
			"monopoly_sashimi_h_ani_01",
			"monopoly_sashimi_h_ani_02",
			"monopoly_sashimi_g_ani_01",
			"monopoly_sashimi_g_ani_02",
			"monopoly_sashimi_c_ani_01",
		}

		// 鑑定師-----end

		// 快問快答-----start
		qafields = []string{
			"user_id",
			"activity_id",
			"game_id",
			"game",
			"topic",
			"skin",
			"music",
			"game_status",
			"game_order",
			"title",
			"people",
			"max_people",
			"allow",
			"limit_time",
			"second",
			"first_prize",
			"second_prize",
			"third_prize",
			"general_prize",
			"game_round",
			"game_second",
			"game_attend",
			"edit_times",

			"qa_bgm_start",  // 遊戲開始
			"qa_bgm_gaming", // 遊戲進行中
			"qa_bgm_end",    // 遊戲結束

			"qa_classic_h_pic_01",
			"qa_classic_h_pic_02",
			"qa_classic_h_pic_03",
			"qa_classic_h_pic_04",
			"qa_classic_h_pic_05",
			"qa_classic_h_pic_06",
			"qa_classic_h_pic_07",
			"qa_classic_h_pic_08",
			"qa_classic_h_pic_09",
			"qa_classic_h_pic_10",
			"qa_classic_h_pic_11",
			"qa_classic_h_pic_12",
			"qa_classic_h_pic_13",
			"qa_classic_h_pic_14",
			"qa_classic_h_pic_15",
			"qa_classic_h_pic_16",
			"qa_classic_h_pic_17",
			"qa_classic_h_pic_18",
			"qa_classic_h_pic_19",
			"qa_classic_h_pic_20",
			"qa_classic_h_pic_21",
			"qa_classic_h_pic_22",
			"qa_classic_g_pic_01",
			"qa_classic_g_pic_02",
			"qa_classic_g_pic_03",
			"qa_classic_g_pic_04",
			"qa_classic_g_pic_05",
			"qa_classic_c_pic_01",
			"qa_classic_h_ani_01",
			"qa_classic_h_ani_02",
			"qa_classic_g_ani_01",
			"qa_classic_g_ani_02",

			"qa_electric_h_pic_01",
			"qa_electric_h_pic_02",
			"qa_electric_h_pic_03",
			"qa_electric_h_pic_04",
			"qa_electric_h_pic_05",
			"qa_electric_h_pic_06",
			"qa_electric_h_pic_07",
			"qa_electric_h_pic_08",
			"qa_electric_h_pic_09",
			"qa_electric_h_pic_10",
			"qa_electric_h_pic_11",
			"qa_electric_h_pic_12",
			"qa_electric_h_pic_13",
			"qa_electric_h_pic_14",
			"qa_electric_h_pic_15",
			"qa_electric_h_pic_16",
			"qa_electric_h_pic_17",
			"qa_electric_h_pic_18",
			"qa_electric_h_pic_19",
			"qa_electric_h_pic_20",
			"qa_electric_h_pic_21",
			"qa_electric_h_pic_22",
			"qa_electric_h_pic_23",
			"qa_electric_h_pic_24",
			"qa_electric_h_pic_25",
			"qa_electric_h_pic_26",
			"qa_electric_g_pic_01",
			"qa_electric_g_pic_02",
			"qa_electric_g_pic_03",
			"qa_electric_g_pic_04",
			"qa_electric_g_pic_05",
			"qa_electric_g_pic_06",
			"qa_electric_g_pic_07",
			"qa_electric_g_pic_08",
			"qa_electric_g_pic_09",
			"qa_electric_c_pic_01",
			"qa_electric_h_ani_01",
			"qa_electric_h_ani_02",
			"qa_electric_h_ani_03",
			"qa_electric_h_ani_04",
			"qa_electric_h_ani_05",
			"qa_electric_g_ani_01",
			"qa_electric_g_ani_02",
			"qa_electric_c_ani_01",

			"qa_moonfestival_h_pic_01",
			"qa_moonfestival_h_pic_02",
			"qa_moonfestival_h_pic_03",
			"qa_moonfestival_h_pic_04",
			"qa_moonfestival_h_pic_05",
			"qa_moonfestival_h_pic_06",
			"qa_moonfestival_h_pic_07",
			"qa_moonfestival_h_pic_08",
			"qa_moonfestival_h_pic_09",
			"qa_moonfestival_h_pic_10",
			"qa_moonfestival_h_pic_11",
			"qa_moonfestival_h_pic_12",
			"qa_moonfestival_h_pic_13",
			"qa_moonfestival_h_pic_14",
			"qa_moonfestival_h_pic_15",
			"qa_moonfestival_h_pic_16",
			"qa_moonfestival_h_pic_17",
			"qa_moonfestival_h_pic_18",
			"qa_moonfestival_h_pic_19",
			"qa_moonfestival_h_pic_20",
			"qa_moonfestival_h_pic_21",
			"qa_moonfestival_h_pic_22",
			"qa_moonfestival_h_pic_23",
			"qa_moonfestival_h_pic_24",
			"qa_moonfestival_g_pic_01",
			"qa_moonfestival_g_pic_02",
			"qa_moonfestival_g_pic_03",
			"qa_moonfestival_g_pic_04",
			"qa_moonfestival_g_pic_05",
			"qa_moonfestival_c_pic_01",
			"qa_moonfestival_c_pic_02",
			"qa_moonfestival_c_pic_03",
			"qa_moonfestival_h_ani_01",
			"qa_moonfestival_h_ani_02",
			"qa_moonfestival_g_ani_01",
			"qa_moonfestival_g_ani_02",
			"qa_moonfestival_g_ani_03",

			"qa_newyear_dragon_h_pic_01",
			"qa_newyear_dragon_h_pic_02",
			"qa_newyear_dragon_h_pic_03",
			"qa_newyear_dragon_h_pic_04",
			"qa_newyear_dragon_h_pic_05",
			"qa_newyear_dragon_h_pic_06",
			"qa_newyear_dragon_h_pic_07",
			"qa_newyear_dragon_h_pic_08",
			"qa_newyear_dragon_h_pic_09",
			"qa_newyear_dragon_h_pic_10",
			"qa_newyear_dragon_h_pic_11",
			"qa_newyear_dragon_h_pic_12",
			"qa_newyear_dragon_h_pic_13",
			"qa_newyear_dragon_h_pic_14",
			"qa_newyear_dragon_h_pic_15",
			"qa_newyear_dragon_h_pic_16",
			"qa_newyear_dragon_h_pic_17",
			"qa_newyear_dragon_h_pic_18",
			"qa_newyear_dragon_h_pic_19",
			"qa_newyear_dragon_h_pic_20",
			"qa_newyear_dragon_h_pic_21",
			"qa_newyear_dragon_h_pic_22",
			"qa_newyear_dragon_h_pic_23",
			"qa_newyear_dragon_h_pic_24",
			"qa_newyear_dragon_g_pic_01",
			"qa_newyear_dragon_g_pic_02",
			"qa_newyear_dragon_g_pic_03",
			"qa_newyear_dragon_g_pic_04",
			"qa_newyear_dragon_g_pic_05",
			"qa_newyear_dragon_g_pic_06",
			"qa_newyear_dragon_c_pic_01",
			"qa_newyear_dragon_h_ani_01",
			"qa_newyear_dragon_h_ani_02",
			"qa_newyear_dragon_g_ani_01",
			"qa_newyear_dragon_g_ani_02",
			"qa_newyear_dragon_g_ani_03",
			"qa_newyear_dragon_c_ani_01",

			"qa_1", "qa_1_options", "qa_1_answer", "qa_1_score",
			"qa_2", "qa_2_options", "qa_2_answer", "qa_2_score",
			"qa_3", "qa_3_options", "qa_3_answer", "qa_3_score",
			"qa_4", "qa_4_options", "qa_4_answer", "qa_4_score",
			"qa_5", "qa_5_options", "qa_5_answer", "qa_5_score",
			"qa_6", "qa_6_options", "qa_6_answer", "qa_6_score",
			"qa_7", "qa_7_options", "qa_7_answer", "qa_7_score",
			"qa_8", "qa_8_options", "qa_8_answer", "qa_8_score",
			"qa_9", "qa_9_options", "qa_9_answer", "qa_9_score",
			"qa_10", "qa_10_options", "qa_10_answer", "qa_10_score",
			"qa_11", "qa_11_options", "qa_11_answer", "qa_11_score",
			"qa_12", "qa_12_options", "qa_12_answer", "qa_12_score",
			"qa_13", "qa_13_options", "qa_13_answer", "qa_13_score",
			"qa_14", "qa_14_options", "qa_14_answer", "qa_14_score",
			"qa_15", "qa_15_options", "qa_15_answer", "qa_15_score",
			"qa_16", "qa_16_options", "qa_16_answer", "qa_16_score",
			"qa_17", "qa_17_options", "qa_17_answer", "qa_17_score",
			"qa_18", "qa_18_options", "qa_18_answer", "qa_18_score",
			"qa_19", "qa_19_options", "qa_19_answer", "qa_19_score",
			"qa_20", "qa_20_options", "qa_20_answer", "qa_20_score",

			"qa_round", "qa_second",  "total_qa",
			// "qa_people",
		}

		// 快問快答-----end

		// 搖紅包-----start
		redpackfields = []string{
			"user_id",
			"activity_id",
			"game_id",
			"game",
			"topic",
			"skin",
			"music",
			"game_status",
			"game_order",
			"title",
			"people",
			"max_people",
			"allow",
			"limit_time",
			"second",
			"percent",
			"game_round",
			"game_second",
			"game_attend",
			"edit_times",

			"redpack_bgm_start",
			"redpack_bgm_gaming",
			"redpack_bgm_end",

			"redpack_classic_h_pic_01",
			"redpack_classic_h_pic_02",
			"redpack_classic_h_pic_03",
			"redpack_classic_h_pic_04",
			"redpack_classic_h_pic_05",
			"redpack_classic_h_pic_06",
			"redpack_classic_h_pic_07",
			"redpack_classic_h_pic_08",
			"redpack_classic_h_pic_09",
			"redpack_classic_h_pic_10",
			"redpack_classic_h_pic_11",
			"redpack_classic_h_pic_12",
			"redpack_classic_h_pic_13",
			"redpack_classic_g_pic_01",
			"redpack_classic_g_pic_02",
			"redpack_classic_g_pic_03",
			"redpack_classic_h_ani_01",
			"redpack_classic_h_ani_02",
			"redpack_classic_g_ani_01",
			"redpack_classic_g_ani_02",
			"redpack_classic_g_ani_03",

			"redpack_cherry_h_pic_01",
			"redpack_cherry_h_pic_02",
			"redpack_cherry_h_pic_03",
			"redpack_cherry_h_pic_04",
			"redpack_cherry_h_pic_05",
			"redpack_cherry_h_pic_06",
			"redpack_cherry_h_pic_07",
			"redpack_cherry_g_pic_01",
			"redpack_cherry_g_pic_02",
			"redpack_cherry_h_ani_01",
			"redpack_cherry_h_ani_02",
			"redpack_cherry_g_ani_01",
			"redpack_cherry_g_ani_02",

			"redpack_christmas_h_pic_01",
			"redpack_christmas_h_pic_02",
			"redpack_christmas_h_pic_03",
			"redpack_christmas_h_pic_04",
			"redpack_christmas_h_pic_05",
			"redpack_christmas_h_pic_06",
			"redpack_christmas_h_pic_07",
			"redpack_christmas_h_pic_08",
			"redpack_christmas_h_pic_09",
			"redpack_christmas_h_pic_10",
			"redpack_christmas_h_pic_11",
			"redpack_christmas_h_pic_12",
			"redpack_christmas_h_pic_13",
			"redpack_christmas_g_pic_01",
			"redpack_christmas_g_pic_02",
			"redpack_christmas_g_pic_03",
			"redpack_christmas_g_pic_04",
			"redpack_christmas_c_pic_01",
			"redpack_christmas_c_pic_02",
			"redpack_christmas_c_ani_01",
		}

		// 搖紅包-----end

		// 套紅包-----start
		ropepackfields = []string{
			"user_id",
			"activity_id",
			"game_id",
			"game",
			"topic",
			"skin",
			"music",
			"game_status",
			"game_order",
			"title",
			"people",
			"max_people",
			"allow",
			"limit_time",
			"second",
			"percent",
			"game_round",
			"game_second",
			"game_attend",
			"edit_times",

			"ropepack_bgm_start",
			"ropepack_bgm_gaming",
			"ropepack_bgm_end",

			"ropepack_classic_h_pic_01",
			"ropepack_classic_h_pic_02",
			"ropepack_classic_h_pic_03",
			"ropepack_classic_h_pic_04",
			"ropepack_classic_h_pic_05",
			"ropepack_classic_h_pic_06",
			"ropepack_classic_h_pic_07",
			"ropepack_classic_h_pic_08",
			"ropepack_classic_h_pic_09",
			"ropepack_classic_h_pic_10",
			"ropepack_classic_g_pic_01",
			"ropepack_classic_g_pic_02",
			"ropepack_classic_g_pic_03",
			"ropepack_classic_g_pic_04",
			"ropepack_classic_g_pic_05",
			"ropepack_classic_g_pic_06",
			"ropepack_classic_h_ani_01",
			"ropepack_classic_g_ani_01",
			"ropepack_classic_g_ani_02",
			"ropepack_classic_c_ani_01",

			"ropepack_newyear_rabbit_h_pic_01",
			"ropepack_newyear_rabbit_h_pic_02",
			"ropepack_newyear_rabbit_h_pic_03",
			"ropepack_newyear_rabbit_h_pic_04",
			"ropepack_newyear_rabbit_h_pic_05",
			"ropepack_newyear_rabbit_h_pic_06",
			"ropepack_newyear_rabbit_h_pic_07",
			"ropepack_newyear_rabbit_h_pic_08",
			"ropepack_newyear_rabbit_h_pic_09",
			"ropepack_newyear_rabbit_g_pic_01",
			"ropepack_newyear_rabbit_g_pic_02",
			"ropepack_newyear_rabbit_g_pic_03",
			"ropepack_newyear_rabbit_h_ani_01",
			"ropepack_newyear_rabbit_g_ani_01",
			"ropepack_newyear_rabbit_g_ani_02",
			"ropepack_newyear_rabbit_g_ani_03",
			"ropepack_newyear_rabbit_c_ani_01",
			"ropepack_newyear_rabbit_c_ani_02",

			"ropepack_moonfestival_h_pic_01",
			"ropepack_moonfestival_h_pic_02",
			"ropepack_moonfestival_h_pic_03",
			"ropepack_moonfestival_h_pic_04",
			"ropepack_moonfestival_h_pic_05",
			"ropepack_moonfestival_h_pic_06",
			"ropepack_moonfestival_h_pic_07",
			"ropepack_moonfestival_h_pic_08",
			"ropepack_moonfestival_h_pic_09",
			"ropepack_moonfestival_g_pic_01",
			"ropepack_moonfestival_g_pic_02",
			"ropepack_moonfestival_c_pic_01",
			"ropepack_moonfestival_h_ani_01",
			"ropepack_moonfestival_g_ani_01",
			"ropepack_moonfestival_g_ani_02",
			"ropepack_moonfestival_c_ani_01",
			"ropepack_moonfestival_c_ani_02",

			"ropepack_3D_h_pic_01",
			"ropepack_3D_h_pic_02",
			"ropepack_3D_h_pic_03",
			"ropepack_3D_h_pic_04",
			"ropepack_3D_h_pic_05",
			"ropepack_3D_h_pic_06",
			"ropepack_3D_h_pic_07",
			"ropepack_3D_h_pic_08",
			"ropepack_3D_h_pic_09",
			"ropepack_3D_h_pic_10",
			"ropepack_3D_h_pic_11",
			"ropepack_3D_h_pic_12",
			"ropepack_3D_h_pic_13",
			"ropepack_3D_h_pic_14",
			"ropepack_3D_h_pic_15",
			"ropepack_3D_g_pic_01",
			"ropepack_3D_g_pic_02",
			"ropepack_3D_g_pic_03",
			"ropepack_3D_g_pic_04",
			"ropepack_3D_h_ani_01",
			"ropepack_3D_h_ani_02",
			"ropepack_3D_h_ani_03",
			"ropepack_3D_g_ani_01",
			"ropepack_3D_g_ani_02",
			"ropepack_3D_c_ani_01",
		}

		// 套紅包-----end

		// 拔河遊戲-----start
		tugofwarfields = []string{
			"user_id",
			"activity_id",
			"game_id",
			"game",
			"topic",
			"skin",
			"music",
			"game_status",
			"game_order",
			"title",
			"people",
			"max_people",
			"allow",
			"limit_time",
			"second",
			"allow_choose_team",
			"left_team_name",
			"right_team_name",
			"left_team_picture",
			"right_team_picture",
			"prize",
			"same_people",
			"game_round",
			"game_second",
			"game_attend",
			"edit_times",

			"tugofwar_bgm_start",  // 遊戲開始
			"tugofwar_bgm_gaming", // 遊戲進行中
			"tugofwar_bgm_end",    // 遊戲結束

			"tugofwar_classic_h_pic_01",
			"tugofwar_classic_h_pic_02",
			"tugofwar_classic_h_pic_03",
			"tugofwar_classic_h_pic_04",
			"tugofwar_classic_h_pic_05",
			"tugofwar_classic_h_pic_06",
			"tugofwar_classic_h_pic_07",
			"tugofwar_classic_h_pic_08",
			"tugofwar_classic_h_pic_09",
			"tugofwar_classic_h_pic_10",
			"tugofwar_classic_h_pic_11",
			"tugofwar_classic_h_pic_12",
			"tugofwar_classic_h_pic_13",
			"tugofwar_classic_h_pic_14",
			"tugofwar_classic_h_pic_15",
			"tugofwar_classic_h_pic_16",
			"tugofwar_classic_h_pic_17",
			"tugofwar_classic_h_pic_18",
			"tugofwar_classic_h_pic_19",
			"tugofwar_classic_g_pic_01",
			"tugofwar_classic_g_pic_02",
			"tugofwar_classic_g_pic_03",
			"tugofwar_classic_g_pic_04",
			"tugofwar_classic_g_pic_05",
			"tugofwar_classic_g_pic_06",
			"tugofwar_classic_g_pic_07",
			"tugofwar_classic_g_pic_08",
			"tugofwar_classic_g_pic_09",
			"tugofwar_classic_h_ani_01",
			"tugofwar_classic_h_ani_02",
			"tugofwar_classic_h_ani_03",
			"tugofwar_classic_c_ani_01",

			"tugofwar_school_h_pic_01",
			"tugofwar_school_h_pic_02",
			"tugofwar_school_h_pic_03",
			"tugofwar_school_h_pic_04",
			"tugofwar_school_h_pic_05",
			"tugofwar_school_h_pic_06",
			"tugofwar_school_h_pic_07",
			"tugofwar_school_h_pic_08",
			"tugofwar_school_h_pic_09",
			"tugofwar_school_h_pic_10",
			"tugofwar_school_h_pic_11",
			"tugofwar_school_h_pic_12",
			"tugofwar_school_h_pic_13",
			"tugofwar_school_h_pic_14",
			"tugofwar_school_h_pic_15",
			"tugofwar_school_h_pic_16",
			"tugofwar_school_h_pic_17",
			"tugofwar_school_h_pic_18",
			"tugofwar_school_h_pic_19",
			"tugofwar_school_h_pic_20",
			"tugofwar_school_h_pic_21",
			"tugofwar_school_h_pic_22",
			"tugofwar_school_h_pic_23",
			"tugofwar_school_h_pic_24",
			"tugofwar_school_h_pic_25",
			"tugofwar_school_h_pic_26",
			"tugofwar_school_g_pic_01",
			"tugofwar_school_g_pic_02",
			"tugofwar_school_g_pic_03",
			"tugofwar_school_g_pic_04",
			"tugofwar_school_g_pic_05",
			"tugofwar_school_g_pic_06",
			"tugofwar_school_g_pic_07",
			"tugofwar_school_c_pic_01",
			"tugofwar_school_c_pic_02",
			"tugofwar_school_c_pic_03",
			"tugofwar_school_c_pic_04",
			"tugofwar_school_h_ani_01",
			"tugofwar_school_h_ani_02",
			"tugofwar_school_h_ani_03",
			"tugofwar_school_h_ani_04",
			"tugofwar_school_h_ani_05",
			"tugofwar_school_h_ani_06",
			"tugofwar_school_h_ani_07",

			"tugofwar_christmas_h_pic_01",
			"tugofwar_christmas_h_pic_02",
			"tugofwar_christmas_h_pic_03",
			"tugofwar_christmas_h_pic_04",
			"tugofwar_christmas_h_pic_05",
			"tugofwar_christmas_h_pic_06",
			"tugofwar_christmas_h_pic_07",
			"tugofwar_christmas_h_pic_08",
			"tugofwar_christmas_h_pic_09",
			"tugofwar_christmas_h_pic_10",
			"tugofwar_christmas_h_pic_11",
			"tugofwar_christmas_h_pic_12",
			"tugofwar_christmas_h_pic_13",
			"tugofwar_christmas_h_pic_14",
			"tugofwar_christmas_h_pic_15",
			"tugofwar_christmas_h_pic_16",
			"tugofwar_christmas_h_pic_17",
			"tugofwar_christmas_h_pic_18",
			"tugofwar_christmas_h_pic_19",
			"tugofwar_christmas_h_pic_20",
			"tugofwar_christmas_h_pic_21",
			"tugofwar_christmas_g_pic_01",
			"tugofwar_christmas_g_pic_02",
			"tugofwar_christmas_g_pic_03",
			"tugofwar_christmas_g_pic_04",
			"tugofwar_christmas_g_pic_05",
			"tugofwar_christmas_g_pic_06",
			"tugofwar_christmas_c_pic_01",
			"tugofwar_christmas_c_pic_02",
			"tugofwar_christmas_c_pic_03",
			"tugofwar_christmas_c_pic_04",
			"tugofwar_christmas_h_ani_01",
			"tugofwar_christmas_h_ani_02",
			"tugofwar_christmas_h_ani_03",
			"tugofwar_christmas_c_ani_01",
			"tugofwar_christmas_c_ani_02",
		}

		// 拔河遊戲-----end

		// 投票-----start
		votefields = []string{
			"user_id",
			"activity_id",
			"game_id",
			"game",
			"topic",
			"skin",
			"music",
			"game_status",
			"game_order",
			"title",
			"title_switch",
			"vote_screen",
			"vote_times",
			"vote_method",
			"arrangement_guest",
			"vote_method_player",
			"vote_restriction",
			"prize",
			"avatar_shape",
			"auto_play",
			"show_rank",
			"vote_start_time",
			"vote_end_time",
			"game_round",
			"game_second",
			"game_attend",
			"edit_times",

			"vote_classic_h_pic_01",
			"vote_classic_h_pic_02",
			"vote_classic_h_pic_03",
			"vote_classic_h_pic_04",
			"vote_classic_h_pic_05",
			"vote_classic_h_pic_06",
			"vote_classic_h_pic_07",
			"vote_classic_h_pic_08",
			"vote_classic_h_pic_09",
			"vote_classic_h_pic_10",
			"vote_classic_h_pic_11",
			"vote_classic_h_pic_13",
			"vote_classic_h_pic_14",
			"vote_classic_h_pic_15",
			"vote_classic_h_pic_16",
			"vote_classic_h_pic_17",
			"vote_classic_h_pic_18",
			"vote_classic_h_pic_19",
			"vote_classic_h_pic_20",
			"vote_classic_h_pic_21",
			"vote_classic_h_pic_23",
			"vote_classic_h_pic_24",
			"vote_classic_h_pic_25",
			"vote_classic_h_pic_26",
			"vote_classic_h_pic_27",
			"vote_classic_h_pic_28",
			"vote_classic_h_pic_29",
			"vote_classic_h_pic_30",
			"vote_classic_h_pic_31",
			"vote_classic_h_pic_32",
			"vote_classic_h_pic_33",
			"vote_classic_h_pic_34",
			"vote_classic_h_pic_35",
			"vote_classic_h_pic_36",
			"vote_classic_h_pic_37",
			"vote_classic_g_pic_01",
			"vote_classic_g_pic_02",
			"vote_classic_g_pic_03",
			"vote_classic_g_pic_04",
			"vote_classic_g_pic_05",
			"vote_classic_g_pic_06",
			"vote_classic_g_pic_07",
			"vote_classic_c_pic_01",
			"vote_classic_c_pic_02",
			"vote_classic_c_pic_03",
			"vote_classic_c_pic_04",

			// 音樂
			"vote_bgm_gaming", // 遊戲進行中
		}
		// 投票-----end

		// 敲敲樂-----start
		whackmolefields = []string{
			"user_id",
			"activity_id",
			"game_id",
			"game",
			"topic",
			"skin",
			"music",
			"game_status",
			"game_order",
			"title",
			"people",
			"max_people",
			"allow",
			"limit_time",
			"second",
			"first_prize",
			"second_prize",
			"third_prize",
			"general_prize",
			"game_round",
			"game_second",
			"game_attend",
			"edit_times",

			"whackmole_bgm_start",
			"whackmole_bgm_gaming",
			"whackmole_bgm_end",

			"whackmole_classic_h_pic_01",
			"whackmole_classic_h_pic_02",
			"whackmole_classic_h_pic_03",
			"whackmole_classic_h_pic_04",
			"whackmole_classic_h_pic_05",
			"whackmole_classic_h_pic_06",
			"whackmole_classic_h_pic_07",
			"whackmole_classic_h_pic_08",
			"whackmole_classic_h_pic_09",
			"whackmole_classic_h_pic_10",
			"whackmole_classic_h_pic_11",
			"whackmole_classic_h_pic_12",
			"whackmole_classic_h_pic_13",
			"whackmole_classic_h_pic_14",
			"whackmole_classic_h_pic_15",
			"whackmole_classic_g_pic_01",
			"whackmole_classic_g_pic_02",
			"whackmole_classic_g_pic_03",
			"whackmole_classic_g_pic_04",
			"whackmole_classic_g_pic_05",
			"whackmole_classic_c_pic_01",
			"whackmole_classic_c_pic_02",
			"whackmole_classic_c_pic_03",
			"whackmole_classic_c_pic_04",
			"whackmole_classic_c_pic_05",
			"whackmole_classic_c_pic_06",
			"whackmole_classic_c_pic_07",
			"whackmole_classic_c_pic_08",
			"whackmole_classic_c_ani_01",

			"whackmole_halloween_h_pic_01",
			"whackmole_halloween_h_pic_02",
			"whackmole_halloween_h_pic_03",
			"whackmole_halloween_h_pic_04",
			"whackmole_halloween_h_pic_05",
			"whackmole_halloween_h_pic_06",
			"whackmole_halloween_h_pic_07",
			"whackmole_halloween_h_pic_08",
			"whackmole_halloween_h_pic_09",
			"whackmole_halloween_h_pic_10",
			"whackmole_halloween_h_pic_11",
			"whackmole_halloween_h_pic_12",
			"whackmole_halloween_h_pic_13",
			"whackmole_halloween_h_pic_14",
			"whackmole_halloween_h_pic_15",
			"whackmole_halloween_g_pic_01",
			"whackmole_halloween_g_pic_02",
			"whackmole_halloween_g_pic_03",
			"whackmole_halloween_g_pic_04",
			"whackmole_halloween_g_pic_05",
			"whackmole_halloween_c_pic_01",
			"whackmole_halloween_c_pic_02",
			"whackmole_halloween_c_pic_03",
			"whackmole_halloween_c_pic_04",
			"whackmole_halloween_c_pic_05",
			"whackmole_halloween_c_pic_06",
			"whackmole_halloween_c_pic_07",
			"whackmole_halloween_c_pic_08",
			"whackmole_halloween_c_ani_01",

			"whackmole_christmas_h_pic_01",
			"whackmole_christmas_h_pic_02",
			"whackmole_christmas_h_pic_03",
			"whackmole_christmas_h_pic_04",
			"whackmole_christmas_h_pic_05",
			"whackmole_christmas_h_pic_06",
			"whackmole_christmas_h_pic_07",
			"whackmole_christmas_h_pic_08",
			"whackmole_christmas_h_pic_09",
			"whackmole_christmas_h_pic_10",
			"whackmole_christmas_h_pic_11",
			"whackmole_christmas_h_pic_12",
			"whackmole_christmas_h_pic_13",
			"whackmole_christmas_h_pic_14",
			"whackmole_christmas_g_pic_01",
			"whackmole_christmas_g_pic_02",
			"whackmole_christmas_g_pic_03",
			"whackmole_christmas_g_pic_04",
			"whackmole_christmas_g_pic_05",
			"whackmole_christmas_g_pic_06",
			"whackmole_christmas_g_pic_07",
			"whackmole_christmas_g_pic_08",
			"whackmole_christmas_c_pic_01",
			"whackmole_christmas_c_pic_02",
			"whackmole_christmas_c_pic_03",
			"whackmole_christmas_c_pic_04",
			"whackmole_christmas_c_pic_05",
			"whackmole_christmas_c_pic_06",
			"whackmole_christmas_c_pic_07",
			"whackmole_christmas_c_pic_08",
			"whackmole_christmas_c_ani_01",
			"whackmole_christmas_c_ani_02",
		}

	// 敲敲樂-----end
	)

	// 查詢所有活動資料
	// activitys, _ := conn.Query("SELECT * FROM activity;")

	sql := db.Table("activity_game").WithConn(conn).
		LeftJoin(command.Join{
			FieldA:    "activity_game.game_id",
			FieldA1:   "activity_game_redpack_picture.game_id",
			Table:     "activity_game_redpack_picture",
			Operation: "="}).
		LeftJoin(command.Join{
			FieldA:    "activity_game.game_id",
			FieldA1:   "activity_game_ropepack_picture.game_id",
			Table:     "activity_game_ropepack_picture",
			Operation: "="}).
		LeftJoin(command.Join{
			FieldA:    "activity_game.game_id",
			FieldA1:   "activity_game_whack_mole_picture.game_id",
			Table:     "activity_game_whack_mole_picture",
			Operation: "="}).
		LeftJoin(command.Join{
			FieldA:    "activity_game.game_id",
			FieldA1:   "activity_game_lottery_picture.game_id",
			Table:     "activity_game_lottery_picture",
			Operation: "="}).
		LeftJoin(command.Join{
			FieldA:    "activity_game.game_id",
			FieldA1:   "activity_game_monopoly_picture.game_id",
			Table:     "activity_game_monopoly_picture",
			Operation: "="}).
		LeftJoin(command.Join{
			FieldA:    "activity_game.game_id",
			FieldA1:   "activity_game_qa_picture.game_id",
			Table:     "activity_game_qa_picture",
			Operation: "="}).
		LeftJoin(command.Join{
			FieldA:    "activity_game.game_id",
			FieldA1:   "activity_game_qa_picture_2.game_id",
			Table:     "activity_game_qa_picture_2",
			Operation: "="}).
		LeftJoin(command.Join{
			FieldA:    "activity_game.game_id",
			FieldA1:   "activity_game_draw_numbers_picture.game_id",
			Table:     "activity_game_draw_numbers_picture",
			Operation: "="}).
		LeftJoin(command.Join{
			FieldA:    "activity_game.game_id",
			FieldA1:   "activity_game_tugofwar_picture.game_id",
			Table:     "activity_game_tugofwar_picture",
			Operation: "="}).
		LeftJoin(command.Join{
			FieldA:    "activity_game.game_id",
			FieldA1:   "activity_game_bingo_picture.game_id",
			Table:     "activity_game_bingo_picture",
			Operation: "="}).
		LeftJoin(command.Join{
			FieldA:    "activity_game.game_id",
			FieldA1:   "activity_game_vote_picture.game_id",
			Table:     "activity_game_vote_picture",
			Operation: "="}).
		LeftJoin(command.Join{
			FieldA:    "activity_game.game_id",
			FieldA1:   "activity_game_3d_gacha_machine_picture.game_id",
			Table:     "activity_game_3d_gacha_machine_picture",
			Operation: "="}).
		LeftJoin(command.Join{
			FieldA:    "activity_game.game_id",
			FieldA1:   "activity_game_qa.game_id",
			Table:     "activity_game_qa",
			Operation: "="})
		// Where("activity_game.game", "=", "whack_mole") // !!!!!要改!!!!!

		// 處理所有欄位參數allFields
	allFields = utils.AddUniqueStrings(allFields, redpackfields)
	allFields = utils.AddUniqueStrings(allFields, ropepackfields)
	allFields = utils.AddUniqueStrings(allFields, whackmolefields)
	allFields = utils.AddUniqueStrings(allFields, lotteryfields)
	allFields = utils.AddUniqueStrings(allFields, monopolyfields)
	allFields = utils.AddUniqueStrings(allFields, qafields)
	allFields = utils.AddUniqueStrings(allFields, drawNumbersfields)
	allFields = utils.AddUniqueStrings(allFields, tugofwarfields)
	allFields = utils.AddUniqueStrings(allFields, bingofields)
	allFields = utils.AddUniqueStrings(allFields, gachaMachinefields)
	allFields = utils.AddUniqueStrings(allFields, votefields)

	cleanedFields := []string{}
	for _, field := range allFields {
		if field != "game_id" && field != "activity_id" {
			cleanedFields = append(cleanedFields, field)
		}
	}

	items, _ := sql.Select(cleanedFields...).All()
	log.Println("資料數: ", len(items))
	// log.Println("所有欄位: ", allFields)

	for _, item := range items {
		var (
			// activityID = utils.GetString(item["activity_id"], "")
			// gameID     = utils.GetString(item["game_id"], "")
			game   = utils.GetString(item["game"], "")
			fields = make([]string, 0)
		)
		// log.Println(activityID, gameID)

		if game == "redpack" {
			fields = redpackfields
		} else if game == "ropepack" {
			fields = ropepackfields
		} else if game == "whack_mole" {
			fields = whackmolefields
		} else if game == "lottery" {
			fields = lotteryfields
		} else if game == "monopoly" {
			fields = monopolyfields
		} else if game == "QA" {
			fields = qafields
		} else if game == "draw_numbers" {
			fields = drawNumbersfields
		} else if game == "tugofwar" {
			fields = tugofwarfields
		} else if game == "bingo" {
			fields = bingofields
		} else if game == "3DGachaMachine" {
			fields = gachaMachinefields
		} else if game == "vote" {
			fields = votefields
		}

		// 取得mongo中的id資料(遞增處理)
		mongoID, _ := mongoConn.GetNextSequence("activity_game")
		// log.Println("mongoID: ", mongoID)

		filterData := FilterFields(item, fields)
		// 將ID寫入map
		filterData["id"] = mongoID
		// log.Println(filterData["activity_id"], filterData["game_id"])

		data = append(data, filterData)

	}

	_, _ = mongoConn.InsertMany("activity_game", data)
	// log.Println("err: ", err)
}
